import fs from "node:fs/promises";
import path from "node:path";
import { loadConfig, loadIntent, saveIntent } from "./utils/config.js";

const MAX_DEPTH = 2;
const AUTO_GENERATED_COMMENT = "<!-- Auto-generated by `blacksmith map` - updated on each run -->";

const shouldExclude = (name, relativePath, excludePatterns) => {
  if (name === ".git" || name === "node_modules" || name === "dist" || name === "build") {
    return true;
  }

  if (name === ".env" || name.startsWith(".env.")) {
    return true;
  }

  return excludePatterns.some((pattern) => {
    if (pattern.endsWith("/**")) {
      return relativePath.startsWith(pattern.slice(0, -3));
    }

    if (pattern.startsWith("*.")) {
      return relativePath.endsWith(pattern.slice(1));
    }

    return relativePath === pattern || name === pattern;
  });
};

const scanTree = async (cwd, excludePatterns, depth = 0, prefix = "") => {
  if (depth > MAX_DEPTH) {
    return [];
  }

  const entries = (await fs.readdir(cwd, { withFileTypes: true })).sort((left, right) =>
    left.name.localeCompare(right.name)
  );
  const lines = [];

  for (const entry of entries) {
    const relative = path.join(prefix, entry.name);
    if (shouldExclude(entry.name, relative, excludePatterns)) {
      continue;
    }

    lines.push(`${"  ".repeat(depth)}- ${entry.name}${entry.isDirectory() ? "/" : ""}`);

    if (entry.isDirectory()) {
      const nested = await scanTree(path.join(cwd, entry.name), excludePatterns, depth + 1, relative);
      lines.push(...nested);
    }
  }

  return lines;
};

export const generateProjectMap = async (cwd = process.cwd()) => {
  const config = await loadConfig();
  const excludePatterns = config.context?.exclude || [];
  const tree = await scanTree(cwd, excludePatterns);
  return tree.length > 0 ? tree.join("\n") : "- (empty)";
};

export const updateIntentProjectMap = async (cwd = process.cwd()) => {
  const intent = await loadIntent();
  const tree = await generateProjectMap(cwd);
  const replacement = `## File Tree (Project Map)\n${AUTO_GENERATED_COMMENT}\n\`\`\`text\n${tree}\n\`\`\``;
  const updated = intent.replace(/## File Tree \(Project Map\)[\s\S]*$/m, replacement);
  await saveIntent(updated);
  return tree;
};
